### ISSUE TITLE
Install free plugins from WP repo rather than from included zip files

### ISSUE THREAD

**Issue by jeffwalker99** [parallelus/Plugin-Installer-for-Runway#12]
We want to change the way the plugin installer works so that free plugins (such as Sidekick, Ninja Forms and Simple Colorbox for example) are installed from the WordPress plugin repository rather than from zip files included in the theme package.

For free plugins, when you choose them in the Runway admin to set up the plugin installer, currently it goes to the WordPress repository and downloads the zip files into the 'extensions/plugin-installer/plugins' folder. That's what we need to change; what we need now is for it to write references into the JSON file so that it knows what plugins to use, but not have a local copies.

Then, in the standalone theme, when users click Install for any of the free required or recommended plugins it installs it from the WordPress repository.

With regard to updating any of these free plugins, we don’t need to do anything at all with the plugin installer, just let WordPress do its normal update notifications thing.

**Comment by jeffwalker99** [comment]
@alexxgermann 

I changed this issue to High Priority because we are hoping to be able to update Caliber with the new plugin installer in the next few days.

**Comment by lesninsky** [comment]
In order to add the plugin from Wordpress repository it is needed to add the plugin's slug in json-file (  eg - ... "Simple Colorbox":{"required":"false","slug":"simple-colorbox"} ... )
which is the part of plugin's URL in Wodrpress repository - https://wordpress.org/plugins/simple-colorbox/

@jeffwalker99 Could you please test these updates?

**Comment by jeffwalker99** [comment]
@lesninsky 

I'm not sure I understand. Are you saying that I needs to edit a JSON file in addition to these changes?

**Comment by jeffwalker99** [comment]
Okay, no worries, I think I understand now.

**Comment by jeffwalker99** [comment]
@lesninsky

When I activated the FrontRunner child theme for Runway it automatically installed and activated Political Options, Simple Theme Slider, and Static Content Blocks. But It did not install Ninja Forms or Simple Colorbox.

My 'data/F6Pn9FrHNvjX_plugin_installer.json' file in the FrontRunner child theme looks like this...

`{"plugin_options":{"Ninja Forms":{"required":"false","slug":"ninja-forms"},"Political Options":{"required":"true"},"Simple Colorbox":{"required":"false","slug":"simple-colorbox"},"Simple Theme Slider":{"required":"false"},"Static Content Blocks":{"required":"false"}}}`

When I create a standalone theme and do a fresh install, same thing, i.e. When I activated the FrontRunner theme it automatically installed and activated Political Options, Simple Theme Slider, and Static Content Blocks, but It did not install Ninja Forms or Simple Colorbox.

**Comment by lesninsky** [comment]
Fixed automatically install for the plugins from WP repository.

**Comment by jeffwalker99** [comment]
This time it installed Ninja Forms and Simple Colorbox but did not install Political Options, Simple Theme Slider, and Static Content Blocks.

It also displayed some invalid header errors.

It also said that Ninja Forms and Simple Colorbox had been installed and activated, but they aren't activated.

It also spat out some PHP notices...

![2016-05-12_12-52-04](https://cloud.githubusercontent.com/assets/4571369/15213686/bdd4edf8-1840-11e6-9b46-0c912fa44c5d.png)


>Notice: Undefined index: file in /xxx/xxx/xxx/parallelus-frontrunner/wp-content/themes/parallelus-frontrunner/extensions/plugin-installer/settings-object.php on line 151

>Notice: Undefined index: Version in /xxx/xxx/xxx/parallelus-frontrunner/wp-content/themes/parallelus-frontrunner/extensions/plugin-installer/settings-object.php on line 152

>Notice: Undefined index: install_version in /xxx/xxx/xxx/parallelus-frontrunner/wp-content/themes/parallelus-frontrunner/extensions/plugin-installer/settings-object.php on line 153

>Notice: Undefined index: file in /xxx/xxx/xxx/parallelus-frontrunner/wp-content/themes/parallelus-frontrunner/extensions/plugin-installer/settings-object.php on line 151

>Notice: Undefined index: Version in /xxx/xxx/xxx/parallelus-frontrunner/wp-content/themes/parallelus-frontrunner/extensions/plugin-installer/settings-object.php on line 152

>Notice: Undefined index: install_version in /xxx/xxx/xxx/parallelus-frontrunner/wp-content/themes/parallelus-frontrunner/extensions/plugin-installer/settings-object.php on line 153

**Comment by jeffwalker99** [comment]
Forget the last message I posted, I may have forgotten to add the plugin zips to plugin installer. (I've deleted that post now.)

**Comment by jeffwalker99** [comment]
Okay, this is working better now. :)

Except that it is putting up two invalid header error messages; and it says all the plugins have been installed and activated but Ninja Forms and Simple Colorbox are not activated. Also there are some PHP notices...

![2016-05-12_13-03-04](https://cloud.githubusercontent.com/assets/4571369/15213971/387b7058-1842-11e6-993c-a3516cf5ef13.png)

>Notice: Undefined index: file in /Users/jeffw/Sites/parallelus-frontrunner/wp-content/themes/parallelus-frontrunner/extensions/plugin-installer/settings-object.php on line 151

>Notice: Undefined index: Version in /Users/jeffw/Sites/parallelus-frontrunner/wp-content/themes/parallelus-frontrunner/extensions/plugin-installer/settings-object.php on line 152

>Notice: Undefined index: install_version in /Users/jeffw/Sites/parallelus-frontrunner/wp-content/themes/parallelus-frontrunner/extensions/plugin-installer/settings-object.php on line 153

>Notice: Undefined index: file in /Users/jeffw/Sites/parallelus-frontrunner/wp-content/themes/parallelus-frontrunner/extensions/plugin-installer/settings-object.php on line 151

>Notice: Undefined index: Version in /Users/jeffw/Sites/parallelus-frontrunner/wp-content/themes/parallelus-frontrunner/extensions/plugin-installer/settings-object.php on line 152

>Notice: Undefined index: install_version in /Users/jeffw/Sites/parallelus-frontrunner/wp-content/themes/parallelus-frontrunner/extensions/plugin-installer/settings-object.php on line 153

**Comment by jeffwalker99** [comment]
I don't know if I was supposed to test this again or not, but I went ahead and tested it anyway.

It looks to be working great now, except that after the theme has been installed and all plugins are installed and activated, when going to **Plugins > Add New** I'm getting a fatal error...

>Fatal error: Cannot redeclare plugins_api() (previously declared in /xxx/xxx/xxx/xxx/wp-admin/includes/plugin-install.php:101) in /xxx/xxx/xxx/xxx/wp-admin/includes/plugin-install.php on line 183

**Comment by lesninsky** [comment]
Fixed

**Comment by jeffwalker99** [comment]
Great, thanks. This looks to be working pretty well.

If I delete (for whatever reason) the Ninja Forms plugin and/or the Simple Colorbox plugin, I am invited to install them as they are recommended plugins. However, on the Plugin Installer page the check boxes for these plugins are disabled so I can't bulk update both plugins at once, I need to click the Install link for one of the plugins, and then navigate back to the Plugin Installer page to click the Install link for the other plugin.

Is there a reason why we are disabling bulk install for plugins that aren't packaged with the theme?

**Comment by alexxgermann** [comment]
Now for bulk actions the installation is allowed for plugins from WP repository.

**Comment by jeffwalker99** [comment]
Excellent! This is working really well. I've only tested it with FrontRunner so far so I guess I should test also with Vellum, GoExplore! and Caliber just to be on the safe side.

**Comment by jeffwalker99** [comment]
It's working great with Vellum.

**Comment by jeffwalker99** [comment]
It's working great with GoExplore!.

**Comment by jeffwalker99** [comment]
And it works great with Caliber.

@parallelus 

Is there any further testing you think needs doing before we update the plugin installer in Vellum, GoExplore!, FrontRunner and Caliber?

**Comment by parallelus** [comment]
I think we need to do this incrementally. I would start with Vellum because it doesn't have any plugins from the WP repo and it's not as new as GoExplore! and FrontRunner.

If all goes well with that, after a couple days and we have no error reports we can add it to both FrontRunner and GoExplore! which will let us test the repo linking. That's going to also require we make changes from the child theme by including a link to those repos from the Plugin Installer UI. From my experience that JSON file gets a little messy. It tends to hang on to old entries even if the plugins are deleted. Maybe we can just delete out the old JSON file and start fresh by adding back all the plugins for those themes?

If Caliber goes live this week, I may want to do an update with this change included early next week.

**Comment by jeffwalker99** [comment]
Vellum does have one WP repo plugin: Sidekick.

To ready the theme we just have to manually edit the plugin installer JSON file and add the `slug` bit for the WP repo plugins. See here → https://github.com/parallelus/Plugin-Installer-for-Runway/issues/12#issuecomment-218185271 That's what I did when testing, and it works.

For future themes, the Plugin Installer extension UI may have to be adjusted so that it writes out the correct stuff; currently I don't think it does (hence the need for manual editing).

Vellum has only just been updated today. I think we should leave it at least a week until we put out another update?

**Comment by jeffwalker99** [comment]
Unless we do a silent update? After all, it only affects new customers?

**Comment by parallelus** [comment]
Yeah, a silent update is good because we're not including any new features, fixes or other changes that impact the customer. This is really an update for us.

**Comment by jeffwalker99** [comment]
Okay, I'll do this today.
