### ISSUE TITLE
Automatically install plugins when theme first activated

### ISSUE THREAD

**Issue by jeffwalker99** [parallelus/Plugin-Installer-for-Runway#13]
We want to change the way the plugin installer works so that when the theme is first activated (and only when the theme is first activated) it automatically installs and activates all of the theme’s required and recommended plugins. (So this is one-time thing.)

One idea we've had is that directly after activation we load the starter kits page, and while  the plugins are being automatically installed and activated we put up a "We're preparing the theme for your WordPress install." modal, or something like that?

**Comment by alexxgermann** [comment]
@jeffwalker99 Could you please test these updates?

**Comment by jeffwalker99** [comment]
@alexxgermann 

I made a fresh install of WordPress, copied the 'parallelus-go-explore' folder into 'wp-content/themes' and then replaced the 'extensions/plugin-installer' folder with the latest development version. When I activated the GoExplore! theme nothing happened except that the GoExplore! theme was activated.

Am I testing this the right way, or is there a special procedure I should follow?

**Comment by jeffwalker99** [comment]
And in **Settings > Plugin Installer** it says "No plugins to install or activate."

**Comment by alexxgermann** [comment]
Could you please check the folder 'extensions/plugin-installer/plugins' for the theme - there should be zip-files of necessary plugins in it. In develop repo 'Plugin-Installer-for-Runway/plugin-installer' they are missed - perhaps this is the cause why nothing has been installed.

**Comment by jeffwalker99** [comment]
D'oh! (blush)

**Comment by jeffwalker99** [comment]
I tested this with GoExplore! and it works great.

A question...

Can we prevent the messages I've outlined in the following screenshot from being displayed?

![2016-05-05_15-28-26](https://cloud.githubusercontent.com/assets/4571369/15046280/cebea3b2-12d6-11e6-9c23-68e4ad4bb183.png)

They are a bit confusing.

**Comment by parallelus** [comment]
I'd also like it if we could combine those success messages into a single message:

*The following plugins were installed and activated successfully: **Travel Destinations**, **Ninja Forms**, **Sidekick**, ...*

**Comment by jeffwalker99** [comment]
Yes, I've also just tested this in Vellum and all the messages push the starter kits way down the page. If we can just have the "please wait" message box with the spinner in it while the plugiuns are being installed, and when that's completed the sibgle message box that Andy wants, that will be great because then there's no risk that anyione will miss the starter kits.

**Comment by jeffwalker99** [comment]
Thanks! This is working now the way Andy suggested.
