### ISSUE TITLE
Can't update Ninja Forms from "Plugins > Installed Plugins"

### ISSUE THREAD

**Issue by jeffwalker99** [parallelus/Plugin-Installer-for-Runway#20]
Looks like there may be a problem with the plugin installer extension?

In **Plugins > Installed Plugins** I can't update Ninja Forms...

![ninja1](https://cloud.githubusercontent.com/assets/4571369/16265766/1a55a7cc-3879-11e6-8d5a-a69e12e5dc17.png)

![ninja2](https://cloud.githubusercontent.com/assets/4571369/16265769/1e0cc152-3879-11e6-99d5-f04a3aa609f4.png)

But it updated okay from **Dashboard > Updates**.

**Comment by alexxgermann** [comment]
I've noticed, that outdated version of "plugin-installer" is used on http://imnoexpert.net/frontrunner - it doesnt match the current version of extension in master and develop theme repo branches. Usage of current "plugin-installer" extension version fixes the issue.

**Comment by jeffwalker99** [comment]
Okay, thanks, I'll update the plugin installer extension and test it again.

**Comment by jeffwalker99** [comment]
Hm. After updating the plugin installer extension with the current development version I'm getting weird shit happening. So then I reverted to v0.9.1 and then the Ninja Forms plugin updated okay from **Plugins > Installed Plugins**.

This needs further testing so for the moment I'm going to remove the "fixed" label.

**Comment by jeffwalker99** [comment]
**NOTE TO SELF:** Ninja Forms v2.9.50 is spitting out PHP notices so this might be the cause of the odd behaviour I've been seeing.

**Comment by jeffwalker99** [comment]
It appears that this problem is being caused by Ninja Forms spitting out PHP notices - i.e. when WP_DEBUG is set to false the problems go away - so I'm closing this issue now.
