### ISSUE TITLE
Disable the auto-install function

### ISSUE THREAD

**Issue by jeffwalker99** [parallelus/Plugin-Installer-for-Runway#22]
Please disable the auto-install function, Envato doesn't like it.

**Comment by alexxgermann** [comment]
I have disabled the auto-install function. 
@jeffwalker99 Could you please test these changes? 
Should I completely remove this functionality from Plugin installer?

**Comment by jeffwalker99** [comment]
>Should I completely remove this functionality from Plugin installer?

Let's try just disabling it first, see if that makes it past Envato.

>@jeffwalker99 Could you please test these changes? 

I'll do that now....

**Comment by jeffwalker99** [comment]
Updating the theme is working okay.

Now testing a fresh install....

**Comment by alexxgermann** [comment]
@jeffwalker99 
Now auto-activate function should work only for "required" plugins. Could you please test these changes

**Comment by jeffwalker99** [comment]
This is working okay with FrontRunner.

I'll test it with other themes when I an preparing updates for those themes.

**Comment by jeffwalker99** [comment]
Working okay with GoExplore!.
