### ISSUE TITLE
The use of alternatives for ZipArchive upon converting extension to plugin

### ISSUE THREAD

**Issue by alexxgermann** [parallelus/Plugin-Installer-for-Runway#28]
Previously (#11) the alternative approach for extracting plugins from zip archives has been implemented when class ZipArchive is missing. In order to convert extension to plugin ZipArchive is still being used.

**Comment by alexxgermann** [comment]
@jeffwalker99 Could you please test these changes?
You have to comment these strings in the .../extensions/plugin-installer/settings-object.php file (lines 351-360) for testing:
```
//if ( class_exists( 'ZipArchive', false ) ) {
//	$z = new ZipArchive();
//	if ( $z->open( $zipPath, ZIPARCHIVE::CREATE ) ) {
//		$z->addEmptyDir( $extension );
//		$z->addFromString( $extension . '/' . $extension . '.php', $ext );
//		$z->addFromString( $extension . '/load-extension.php', $load_extension );
//		self::ext_to_plugin( $sourcePath, $z, strlen( "$parentPath/" ), $extension . '/' );
//		$z->close();
//	}
//} else {
	require_once( ABSPATH . 'wp-admin/includes/class-pclzip.php' );

	$temp_dir          = get_temp_dir();
	$tmp_extension_dir = get_temp_dir() . 'extensions/' . $extension;

	$wp_filesystem->rmdir( $temp_dir . 'extensions' );
	$wp_filesystem->mkdir( $temp_dir . 'extensions' );
	$wp_filesystem->mkdir( $tmp_extension_dir );
	$wp_filesystem->mkdir( $tmp_extension_dir . '/' . $extension );

	copy_dir( $sourcePath, $tmp_extension_dir . '/' . $extension );
	$wp_filesystem->put_contents( $tmp_extension_dir . '/' . $extension . '.php', $ext );
	$wp_filesystem->put_contents( $tmp_extension_dir . '/load-extension.php', $load_extension );

	$z = new PclZip( $zipPath );
	$z->create( array( $tmp_extension_dir ), '', $temp_dir . 'extensions' );

	$wp_filesystem->rmdir( get_temp_dir() . 'extensions' );
//}
```

**Comment by jeffwalker99** [comment]
@alexxgermann 

I'm not sure what I am testing here?

I created a fresh WordPress site and installed FrontRunner using the latest development version of the plugin installer (with those lines commented out), and the installation of the theme and plugins completed successfully.

Is that what I needed to test?

**Comment by alexxgermann** [comment]
@jeffwalker99 
This functionality works only on on fresh install of Runway/Liftoff theme. Please go to Settings->Plugin Installer->Extensions, select extension and click the "Allow Install as Plugin" button. After successful archive extraction the selected extension will appear in Plugins

**Comment by jeffwalker99** [comment]
Tested and working!
