### ISSUE TITLE
Plugin Installer can't get the info regarding some archived plugins when use PHP 7

### ISSUE THREAD

**Issue by alexxgermann** [parallelus/Plugin-Installer-for-Runway#30]
Plugin Installer can't get the info regarding an archived plugin, if the plugin doesn't have nested folders and PHP7 (PzlZip) is used.  Static Content Blocks relates to such plugins.

**Comment by alexxgermann** [comment]
@jeffwalker99 Could you please test these changes?
Please comment temporary these strings in the .../extensions/plugin-installer/object.php file (lines 264-268) for testing purposes:
//if ( class_exists( 'ZipArchive', false ) ) {
// $res = $this->unzip_file_ziparchive($plugins_zip_path, $plug_file);
//} else {
$res = $this->unzip_file_pclzip($plugins_zip_path, $plug_file);
//}

**Comment by jeffwalker99** [comment]
I'm not sure what problem I'm looking for?

**Comment by alexxgermann** [comment]
@jeffwalker99 
The best way will be to test on Caliber theme. If you comment the lines that I've mentioned above or switch to PHP7, then warnings should appear in admin dash. If use Plugin Installer with the latest changes, warnings shouldn't appear

**Comment by jeffwalker99** [comment]
Okay, thanks.

**Comment by jeffwalker99** [comment]
Tested and working!

>**Note to self:** I've also tested updating the plugin installer extension so that  Ninja Forms and Simple Colorbox are installed from the WP repo, and that all works okay.

>`{"plugin_options":{"Ninja Forms":{"required":"false","slug":"ninja-forms"},"Simple Colorbox":{"required":"false","slug":"simple-colorbox"},"Static Content Blocks":{"required":"true"},"Simple Theme Portfolio":{"required":"false"},"Live Editor":{"required":"true"}}}`
