### ISSUE TITLE
Screen goes a bit messy when plugin installer is working

### ISSUE THREAD

**Issue by jeffwalker99** [parallelus/Plugin-Installer-for-Runway#32]
I think this behaviour began after the WordPress v4.6 update. You can see that while the plugin installer is working and reporting on its progress, the screen becomes quite messy...

![plugin-installer](https://cloud.githubusercontent.com/assets/4571369/18251234/e0c4fcdc-737f-11e6-9cca-f6f99a21b6e2.png)

Once the plugin installer is finished the screen sorts itself out, but is there any way we can prevent the screen looking so messy while the plugin installer is working?

**Comment by alexxgermann** [comment]
@jeffwalker99 Could you please test these changes?

**Comment by jeffwalker99** [comment]
Much better! Thanks!
