### ISSUE TITLE
PHP notice

### ISSUE THREAD

**Issue by jeffwalker99** [parallelus/Plugin-Installer-for-Runway#40]
I'm seeing this notice on the plugin installer page when I install Beaver Builder Lite...

>Notice: Undefined variable: type in /xxx/xxx/xxx/parallelus-frontrunner/wp-content/themes/parallelus-frontrunner/extensions/plugin-installer/install/class-tgmpa-list-table.php on line 362

**Comment by b-shtybin** [comment]
@jeffwalker99
Could you please test?

**Comment by jeffwalker99** [comment]
@b-shtybin It shouldn't need testing if it is the same fix as in FrontRunner?

**Comment by jeffwalker99** [comment]
@b-shtybin I can't find any commit for this?
