### ISSUE TITLE
Selecting a plugin by link not working

### ISSUE THREAD

**Issue by parallelus** [parallelus/Plugin-Installer-for-Runway#8]
Testing the addition of a plugin from a link rather than a file uploaded is not working. It registers the plugin and recognizes it, however when installing a standalone theme there is no prompt to install the linked plugin. 

The test was done with the linked plugin being a "recommended" however I think the results would be the same for a "required" plugin as well.

**Comment by lesninsky** [comment]
Fixed by commit https://github.com/parallelus/Plugin-Installer-for-Runway/commit/d27f1dd25e2ba280ffc91dd37ff4f499d3307623
